import { useParams, Link, useNavigate } from "react-router-dom";
import { BLOG_POSTS } from "../constants";
import { Calendar, User, ArrowLeft, ArrowRight, Facebook, Twitter, Linkedin, Share2 } from "lucide-react";
import { motion } from "motion/react";
import { useEffect } from "react";

export default function BlogPostPage({ isAr }: { isAr: boolean }) {
  const { id } = useParams();
  const navigate = useNavigate();
  const post = BLOG_POSTS.find((p) => p.id === Number(id));

  const shareUrl = window.location.href;
  const shareTitle = post ? (isAr ? post.titleAr : post.title) : "";

  useEffect(() => {
    if (!post) {
      navigate("/blog");
    }
  }, [post, navigate]);

  if (!post) return null;

  const shareLinks = [
    {
      name: "Facebook",
      icon: <Facebook size={20} />,
      url: `https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(shareUrl)}`,
      color: "hover:bg-blue-600 hover:text-white",
    },
    {
      name: "Twitter",
      icon: <Twitter size={20} />,
      url: `https://twitter.com/intent/tweet?url=${encodeURIComponent(shareUrl)}&text=${encodeURIComponent(shareTitle)}`,
      color: "hover:bg-sky-500 hover:text-white",
    },
    {
      name: "LinkedIn",
      icon: <Linkedin size={20} />,
      url: `https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(shareUrl)}`,
      color: "hover:bg-blue-700 hover:text-white",
    },
  ];

  return (
    <div className="pt-32 pb-20 bg-white min-h-screen">
      <div className="max-w-4xl mx-auto px-6">
        <Link 
          to="/blog" 
          className="inline-flex items-center gap-2 text-emerald-600 font-bold mb-8 hover:gap-3 transition-all"
        >
          {isAr ? <ArrowRight size={18} /> : <ArrowLeft size={18} />}
          {isAr ? "العودة للمدونة" : "Back to Blog"}
        </Link>

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
        >
          <div className="flex items-center gap-4 text-sm text-slate-400 mb-6">
            <span className="bg-emerald-50 text-emerald-600 px-3 py-1 rounded-full font-bold uppercase tracking-wider">
              {isAr ? post.categoryAr : post.category}
            </span>
            <div className="flex items-center gap-2">
              <Calendar size={16} />
              <span>{post.date}</span>
            </div>
            <div className="flex items-center gap-2">
              <User size={16} />
              <span>{isAr ? post.authorAr : post.author}</span>
            </div>
          </div>

          <h1 className="text-4xl md:text-6xl font-bold text-slate-900 mb-10 leading-tight">
            {isAr ? post.titleAr : post.title}
          </h1>

          <div className="aspect-video rounded-3xl overflow-hidden mb-12 shadow-2xl">
            <img 
              src={post.image} 
              alt={post.title} 
              className="w-full h-full object-cover"
              referrerPolicy="no-referrer"
            />
          </div>

          <div className="prose prose-lg max-w-none text-slate-700 leading-relaxed space-y-6">
            <p className="text-xl font-medium text-slate-900 italic border-r-4 border-emerald-500 pr-6 py-2">
              {isAr ? post.excerptAr : post.excerpt}
            </p>
            <div className="whitespace-pre-line">
              {isAr ? post.contentAr : post.content}
            </div>
            <p>
              {isAr 
                ? "هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد النص العربى، حيث يمكنك أن تولد مثل هذا النص أو العديد من النصوص الأخرى إضافة إلى زيادة عدد الحروف التى يولدها التطبيق."
                : "This is a sample text that can be replaced in the same space. This text was generated from the Arabic text generator, where you can generate such text or many other texts in addition to increasing the number of characters generated by the application."}
            </p>
            <p>
              {isAr 
                ? "إذا كنت تحتاج إلى عدد أكبر من الفقرات يتيح لك مولد النص العربى زيادة عدد الفقرات كما تريد، النص لن يبدو مقسما ولا يحوي أخطاء لغوية، مولد النص العربى مفيد لمصممي المواقع على وجه الخصوص، حيث يحتاج التصميم لتجهيزه لنص مسبق."
                : "If you need a larger number of paragraphs, the Arabic text generator allows you to increase the number of paragraphs as you want. The text will not look divided and does not contain linguistic errors. The Arabic text generator is useful for website designers in particular, where the design needs to be prepared for a pre-text."}
            </p>
          </div>

          <div className="mt-20 pt-10 border-t border-slate-100 flex flex-col md:flex-row justify-between items-center gap-8">
            <div className="flex items-center gap-4">
              <div className="w-12 h-12 bg-slate-100 rounded-full flex items-center justify-center text-slate-400">
                <User size={24} />
              </div>
              <div>
                <div className="font-bold text-slate-900">{isAr ? post.authorAr : post.author}</div>
                <div className="text-sm text-slate-500">{isAr ? "مهندس استشاري" : "Consultant Engineer"}</div>
              </div>
            </div>
            
            <div className="flex items-center gap-4">
              <span className="text-sm font-bold text-slate-400 uppercase tracking-widest flex items-center gap-2">
                <Share2 size={16} />
                {isAr ? "مشاركة" : "Share"}
              </span>
              <div className="flex gap-3">
                {shareLinks.map((link) => (
                  <a
                    key={link.name}
                    href={link.url}
                    target="_blank"
                    rel="noopener noreferrer"
                    className={`w-12 h-12 rounded-full bg-slate-50 flex items-center justify-center text-slate-400 transition-all duration-300 ${link.color} shadow-sm`}
                    title={link.name}
                  >
                    {link.icon}
                  </a>
                ))}
              </div>
            </div>
          </div>
        </motion.div>
      </div>
    </div>
  );
}
